### ISSUE TITLE
Домашняя работа №5

### ISSUE THREAD

**Issue by UmanskiyDan** [MIEE-ACS/domashnee-zadanie-no5-UmanskiyDan#1]
Закончено

**Comment by d-makarenko** [comment]
Созданный класс Counter по сути не используется. В самом начале создается несколько экземпляров и на этом все.
Я повторяюсь, конечно, но все же: идея ооп заключается в том, что мы объединяем в классе данные и методы для их обработки. В этом задании у нас есть данные - текущее значение счетчика и методы: увеличить и уменьшить. В твоем решении все размазано по коду класса MainWindow.

Посмотри более правильный вариант решения тут: https://github.com/MIEE-ACS/domashnee-zadanie-no5-Sofya112
